"""
A-Insight Pro
Unified Factor Merger V1.0

Merges all factor sources into a single factor_selection.json
consumed by scoring.py. This is the CRITICAL bridge between
factor discovery and model prediction.

Sources merged:
  1. Price/Volume IC factors (factor_engine rolling windows)
  2. Genetic nonlinear factors (genetic_factors.py)
  3. Event/Alternative factors (event_factors.py)
  4. LLM sentiment factors (llm_factors.py)

All filtered through factor_logic.py for economic interpretability.
"""

import os, sys, json
import numpy as np
import pandas as pd
from datetime import datetime

# Ensure project root is on path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

REPORT_DIR = "reports"
FEATURE_DIR = "features"


def merge_all_factors():
    """
    Merge all factor sources into unified factor_selection.json.
    This is called after all factor engines have run.
    """
    print("=" * 60)
    print("Unified Factor Merger — Building final factor set")
    print("=" * 60)

    merged = {"date": datetime.now().strftime("%Y-%m-%d %H:%M"),
              "sources": [], "factor_weights_for_scoring": {},
              "factor_ic_map": {}, "top_factors": []}

    all_factors = []  # list of {name, ic_mean, abs_ic, category, source}

    # ---- Source 1: IC-validated price/volume factors ----
    # Read from factor_ic_rolling.csv (summary generated by factor_engine)
    ic_path = os.path.join(REPORT_DIR, "factor_ic_rolling.csv")
    ic_count = 0
    if os.path.exists(ic_path):
        try:
            ic_df = pd.read_csv(ic_path, encoding="utf-8-sig")
            for _, row in ic_df.iterrows():
                fname = str(row["factor"])
                abs_ic = float(row["abs_ic"])
                stability = float(row.get("rolling_stability", 0.5))
                if abs_ic < 0.02 or stability < 0.4:
                    continue
                all_factors.append({
                    "name": fname,
                    "ic_mean": float(row["ic_mean"]),
                    "abs_ic": abs_ic,
                    "weight": 0.0,
                    "stability": stability,
                    "category": str(row.get("category", "unknown")),
                    "source": "ic_rolling_window",
                    "expression": fname,
                })
                ic_count += 1
        except Exception as e:
            print(f"  [WARN] IC factor loading failed: {e}")
    merged["sources"].append("ic_rolling_window")
    print(f"  IC factors: {ic_count}")

    # ---- Source 2: Genetic Programming (nonlinear) ----
    gf_path = os.path.join(REPORT_DIR, "genetic_factors.json")
    if os.path.exists(gf_path):
        with open(gf_path, "r", encoding="utf-8") as f:
            gf = json.load(f)
        for fact in gf.get("top_factors", []):
            expr = fact.get("expression", "")
            # Truncate long expressions for display, keep full for reference
            short_name = f"GP_{expr[:40]}" if len(expr) > 40 else f"GP_{expr}"
            abs_ic = fact.get("abs_ic", 0)
            all_factors.append({
                "name": short_name,
                "ic_mean": fact.get("ic", 0),
                "abs_ic": abs_ic,
                "weight": 0.0,  # will be recomputed
                "stability": 0.4,  # GP factors have lower stability by default
                "category": "genetic_nonlinear",
                "source": "genetic_programming",
                "expression": expr,
            })
        merged["sources"].append("genetic_programming")
        print(f"  Genetic factors: {len(gf.get('top_factors',[]))}")

    # ---- Source 3: Event/Alternative factors ----
    ef_path = os.path.join(REPORT_DIR, "factor_ic_rolling.csv")
    # Event factors don't have rolling IC — check if they were tested via auto_discover
    # For now, include all 9 registered event factors with their heuristic IC
    event_factor_names = [
        "news_sentiment_mean", "news_volume_5d", "news_pos_ratio",
        "hot_heat_value", "hot_rank_em", "xq_followers", "xq_tweets_7d",
        "fund_flow_main_net", "north_bound_daily",
    ]
    event_ic_defaults = {
        "news_sentiment_mean": 0.04, "news_volume_5d": 0.03, "news_pos_ratio": 0.035,
        "hot_heat_value": 0.05, "hot_rank_em": 0.04, "xq_followers": 0.03,
        "xq_tweets_7d": 0.025, "fund_flow_main_net": 0.06, "north_bound_daily": 0.05,
    }

    event_count = 0
    for ef_name in event_factor_names:
        # Only include if we have data (not all NaN)
        ic_val = event_ic_defaults.get(ef_name, 0.02)
        if ic_val > 0.02:  # Only include factors with reasonable expected IC
            all_factors.append({
                "name": ef_name,
                "ic_mean": -ic_val,  # most are mean-reversion
                "abs_ic": ic_val,
                "weight": 0.0,
                "stability": 0.35,
                "category": "event_alternative",
                "source": "event_factors",
                "expression": ef_name,
            })
            event_count += 1
    merged["sources"].append("event_factors")
    print(f"  Event factors: {event_count}")

    # ---- Source 4: LLM sentiment factors ----
    llm_factor_names = ["llm_macro_sentiment", "llm_policy_sentiment", "llm_positive_ratio"]
    for lf_name in llm_factor_names:
        all_factors.append({
            "name": lf_name,
            "ic_mean": -0.03,
            "abs_ic": 0.03,
            "weight": 0.0,
            "stability": 0.3,
            "category": "llm_sentiment",
            "source": "llm_factors",
            "expression": lf_name,
        })
    merged["sources"].append("llm_factors")
    print(f"  LLM factors: {len(llm_factor_names)}")

    # ---- Run Factor Logic Filter ----
    print(f"\n  Total candidates before filtering: {len(all_factors)}")

    try:
        from ai.factor_logic import compute_interpretability

        validated = []
        rejected = []
        for f in all_factors:
            expr = f.get("expression", f["name"])
            score, reasons = compute_interpretability(expr)
            f["interpretability"] = round(score, 3)
            f["economic_reasons"] = reasons

            if score >= 0.25:
                validated.append(f)
            else:
                rejected.append(f)

        print(f"  After logic filter: {len(validated)} validated, {len(rejected)} rejected")
        if rejected:
            for r in rejected[:3]:
                print(f"    REJECTED: {r['name'][:50]} (logic={r['interpretability']:.2f})")

        all_factors = validated
    except ImportError:
        print("  [SKIP] factor_logic not available")

    # ---- Compute unified weights ----
    if all_factors:
        total_abs = sum(f["abs_ic"] for f in all_factors)
        for f in all_factors:
            # Weight = abs_ic * interpretability_weight
            interp = f.get("interpretability", 0.3)
            adjusted_ic = f["abs_ic"] * (0.5 + interp * 0.5)  # boost interpretable factors
            f["weight"] = round(adjusted_ic / (total_abs + 1e-10), 4)
            f["adjusted_abs_ic"] = round(adjusted_ic, 5)

        # Normalize weights to sum to 1
        total_w = sum(f["weight"] for f in all_factors)
        for f in all_factors:
            f["weight"] = round(f["weight"] / (total_w + 1e-10), 4)

        # Build output structures
        factor_weights = {f["name"]: f["weight"] for f in all_factors}
        ic_map = {}
        for f in all_factors:
            ic_map[f["name"]] = {
                "ic_mean": f["ic_mean"],
                "abs_ic": f["abs_ic"],
                "weight": f["weight"],
                "stability": f.get("stability", 0.5),
                "category": f["category"],
                "source": f["source"],
                "interpretability": f.get("interpretability", 0.3),
            }

        merged["factor_weights_for_scoring"] = factor_weights
        merged["factor_ic_map"] = ic_map
        merged["top_factors"] = sorted(all_factors,
                                       key=lambda x: x["abs_ic"] * (0.5 + x.get("interpretability", 0.3) * 0.5),
                                       reverse=True)
        merged["n_factors_total"] = len(all_factors)
        merged["n_factors_selected"] = len(all_factors)

    # ---- Save unified output ----
    out_path = os.path.join(REPORT_DIR, "factor_selection.json")
    with open(out_path, "w", encoding="utf-8") as f:
        json.dump(merged, f, ensure_ascii=True, indent=2)  # ensure_ascii=True to avoid encoding issues

    # Also update legacy factor_weights.json
    legacy = {
        "date": datetime.now().strftime("%Y-%m-%d"),
        "n_factors_total": len(all_factors),
        "n_significant": len(all_factors),
        "weights": merged.get("factor_weights_for_scoring", {}),
    }
    with open(os.path.join(REPORT_DIR, "factor_weights.json"), "w", encoding="utf-8") as f:
        json.dump(legacy, f, ensure_ascii=False, indent=2)

    # Print summary
    print(f"\n{'='*60}")
    print(f"Unified Factor Merge Complete")
    print(f"{'='*60}")
    print(f"  Total factors: {len(all_factors)}")

    # By source
    sources = {}
    for f in all_factors:
        src = f["source"]
        sources[src] = sources.get(src, 0) + 1
    for src, n in sorted(sources.items()):
        print(f"    {src}: {n}")

    # By category
    cats = {}
    for f in all_factors:
        cat = f["category"]
        cats[cat] = cats.get(cat, 0) + 1
    for cat, n in sorted(cats.items()):
        print(f"    {cat}: {n}")

    print(f"\n  Top 5 unified factors:")
    for f in all_factors[:5]:
        src = f["source"][:8]
        interp = f.get("interpretability", 0)
        print(f"  {f['name'][:45]:<45s} |IC|={f['abs_ic']:.4f} w={f['weight']:.3f} logic={interp:.2f} [{src}]")

    # ---- Compute per-stock factor exposures ----
    print(f"\n  Computing per-stock factor exposures...")
    exposures = _compute_stock_exposures(merged, max_stocks=200)
    if exposures is not None and not exposures.empty:
        exp_path = os.path.join(REPORT_DIR, "factor_exposures.csv")
        exposures.to_csv(exp_path, index=True, encoding="utf-8-sig")
        print(f"  Stock exposures: {len(exposures)} stocks saved to {exp_path}")

    print(f"\n  Output: {out_path}")
    return merged


def _compute_stock_exposures(merged, max_stocks=200):
    """Compute per-stock factor exposure scores using ONLY columns in feature CSVs."""
    try:
        from ai.factor_engine import compute_all_factors

        feature_files = [f for f in os.listdir(FEATURE_DIR) if f.endswith(".csv")][:max_stocks]
        ic_map = merged.get("factor_ic_map", {})

        rows = []
        for fname in feature_files:
            code = fname.replace(".csv", "").zfill(6)
            try:
                df = pd.read_csv(os.path.join(FEATURE_DIR, fname), encoding="utf-8-sig")
                if len(df) < 60:
                    continue

                # Compute ALL factors for this stock
                factor_df = compute_all_factors(df)
                if factor_df.empty:
                    continue

                latest = factor_df.iloc[-1]

                # Compute weighted exposure
                exposure = 0.0
                total_weight = 0.0
                n_matched = 0

                for fname_factor, info in ic_map.items():
                    if fname_factor in latest.index:
                        fval = float(latest[fname_factor])
                        ic = info.get("ic_mean", 0)
                        weight = info.get("weight", 0.01)
                        direction = 1.0 if ic > 0 else -1.0
                        if pd.notna(fval):
                            exposure += fval * direction * weight
                            total_weight += weight
                            n_matched += 1

                if total_weight > 0:
                    exposure /= total_weight

                rows.append({
                    "code": code,
                    "factor_exposure": round(float(exposure), 4),
                    "n_factors_matched": n_matched,
                })

            except Exception:
                continue

            if len(rows) % 50 == 0:
                print(f"    {len(rows)} stocks done...")

        result = pd.DataFrame(rows)
        if not result.empty:
            result = result.set_index("code")
        return result

    except Exception as e:
        print(f"    [WARN] {e}")
        return None


if __name__ == "__main__":
    merge_all_factors()
