"""
A-Insight Pro
行情更新系统 V3.0

功能:
1. 实时行情保存 realtime
2. 历史日K保护 data
3. 自动生成 features
4. 防止分钟数据污染
"""

import os
import time
import random
import traceback
import requests
import pandas as pd


DATA_DIR = "data"
REALTIME_DIR = "realtime"
FEATURE_DIR = "features"
REPORT_DIR = "reports"

STOCK_LIST = "data/stock_list.csv"

ERROR_FILE = "reports/update_error.log"


# =========================
# 初始化
# =========================

def init():

    os.makedirs(DATA_DIR, exist_ok=True)
    os.makedirs(REALTIME_DIR, exist_ok=True)
    os.makedirs(FEATURE_DIR, exist_ok=True)
    os.makedirs(REPORT_DIR, exist_ok=True)



def log_error(msg):

    with open(
        ERROR_FILE,
        "a",
        encoding="utf-8"
    ) as f:

        f.write(
            msg + "\n"
        )



# =========================
# 股票代码
# =========================

def market_code(code):

    code=str(code).zfill(6)

    if code.startswith(("5","6")):

        return "sh"+code

    return "sz"+code



# =========================
# 获取实时价格
# =========================

def get_price(code):

    url=(
        "https://qt.gtimg.cn/q="
        +
        market_code(code)
    )

    try:

        r=requests.get(
            url,
            timeout=10,
            headers={
                "User-Agent":
                "Mozilla/5.0"
            }
        )


        if r.text.startswith("v_"):

            data=r.text.split("~")

            return {

                "date":
                pd.Timestamp.now()
                .strftime("%Y-%m-%d %H:%M:%S"),

                "price":
                float(data[3])

            }


    except Exception:

        pass


    return None



# =========================
# 保存实时行情
# =========================

def save_realtime(code,row):

    file=os.path.join(
        REALTIME_DIR,
        str(code).zfill(6)+".csv"
    )


    df=pd.DataFrame(
        [row]
    )


    if os.path.exists(file):

        old=pd.read_csv(
            file
        )

        df=pd.concat(
            [
                old,
                df
            ],
            ignore_index=True
        )


    df.to_csv(
        file,
        index=False,
        encoding="utf-8-sig"
    )



# =========================
# 读取历史
# =========================

def load_history(code):

    file=os.path.join(
        DATA_DIR,
        str(code).zfill(6)+".csv"
    )


    if os.path.exists(file):

        try:

            return pd.read_csv(
                file
            )

        except:

            pass


    return pd.DataFrame(
        columns=[
            "date",
            "open",
            "high",
            "low",
            "close",
            "volume"
        ]
    )



# =========================
# 清理异常
# =========================

def clean_history(df):

    if len(df)==0:

        return df


    df=df.copy()


    df["date"]=(
        df["date"]
        .astype(str)
    )


    # 删除14位分钟时间

    df=df[
        ~df["date"]
        .str.match(
            r"^\d{14}$"
        )
    ]



    # 删除成交量0

    if "volume" in df.columns:

        df=df[
            df["volume"]>0
        ]



    return df



# =========================
# features
# =========================

def make_features(df):

    df=df.copy()


    df["return"]=(
        df["close"]
        .pct_change()
    )


    df["ma5"]=(
        df["close"]
        .rolling(5)
        .mean()
    )


    df["ma10"]=(
        df["close"]
        .rolling(10)
        .mean()
    )


    df["ma20"]=(
        df["close"]
        .rolling(20)
        .mean()
    )


    df["ma60"]=(
        df["close"]
        .rolling(60)
        .mean()
    )


    df["volume_change"]=(
        df["volume"]
        .pct_change()
    )


    df["volatility"]=(
        df["return"]
        .rolling(20)
        .std()
    )


    delta=df["close"].diff()


    gain=(
        delta.clip(lower=0)
        .rolling(14)
        .mean()
    )


    loss=(
        -delta.clip(upper=0)
        .rolling(14)
        .mean()
    )


    rs=gain/loss.replace(
        0,
        1e-9
    )


    df["rsi"]=100-(100/(1+rs))


    ema12=(
        df["close"]
        .ewm(
            span=12,
            adjust=False
        )
        .mean()
    )


    ema26=(
        df["close"]
        .ewm(
            span=26,
            adjust=False
        )
        .mean()
    )


    df["macd"]=ema12-ema26


    return df.dropna()



def save_history(code,df):

    code=str(code).zfill(6)


    df.to_csv(
        f"{DATA_DIR}/{code}.csv",
        index=False,
        encoding="utf-8-sig"
    )

    # Features are now generated by data_center/feature_engine.py (Step 2 of pipeline)
    # This avoids the V1/V2 feature column conflict



# =========================
# 主更新
# =========================

def update():

    init()


    print("================")
    print("A-Insight 行情系统 V3.0")
    print("================")


    stocks=pd.read_csv(
        STOCK_LIST,
        dtype={
            "code":str
        }
    )


    stocks["code"]=(
        stocks["code"]
        .str.zfill(6)
    )


    total=len(stocks)


    for i,row in stocks.iterrows():


        code=row["code"]


        print(
            f"[{i+1}/{total}] {code}"
        )


        try:

            market=get_price(code)


            if market is None:

                continue



            # 保存实时

            save_realtime(
                code,
                market
            )


            # 历史保护

            df=load_history(code)


            df=clean_history(df)



            save_history(
                code,
                df
            )


        except Exception:


            log_error(
                traceback.format_exc()
            )


        time.sleep(
            random.uniform(
                0.3,
                0.8
            )
        )


    print("================")
    print("实时行情更新完成")
    print("================")

    # Also sync historical OHLCV data
    sync_history(stocks)


# =========================
# Historical OHLCV sync via akshare
# =========================

def sync_history(stocks):
    """Pull latest historical OHLCV data via akshare and append to data/*.csv."""
    try:
        import akshare as ak
    except ImportError:
        print("akshare not installed, skip history sync")
        return

    print("================")
    print("同步历史K线数据...")
    print("================")

    updated = 0
    for i, row in stocks.iterrows():
        code = row["code"]
        file = os.path.join(DATA_DIR, f"{code}.csv")

        # Determine start date: last date in file + 1 day
        start_date = "20220101"  # default
        if os.path.exists(file):
            try:
                old = pd.read_csv(file, encoding="utf-8-sig")
                if len(old) > 0:
                    last = old["date"].iloc[-1]
                    # Next day
                    from datetime import datetime, timedelta
                    last_dt = datetime.strptime(str(last)[:10], "%Y-%m-%d")
                    start_date = (last_dt + timedelta(days=1)).strftime("%Y%m%d")
            except Exception:
                pass

        today = pd.Timestamp.now().strftime("%Y%m%d")

        # Skip if already up to date
        if start_date >= today:
            continue

        try:
            # Determine symbol prefix: sh for 6xx, sz for 0xx/3xx
            if code.startswith("6"):
                symbol = f"sh{code}"
            else:
                symbol = f"sz{code}"

            new_data = ak.stock_zh_a_hist(
                symbol=code,
                period="daily",
                start_date=start_date,
                end_date=today,
                adjust="qfq"
            )

            if new_data is None or len(new_data) == 0:
                continue

            # Rename columns to match existing format
            new_data = new_data.rename(columns={
                "日期": "date",
                "开盘": "open",
                "最高": "high",
                "最低": "low",
                "收盘": "close",
                "成交量": "volume",
            })

            cols = ["date", "open", "high", "low", "close", "volume"]
            new_data = new_data[[c for c in cols if c in new_data.columns]]
            # Convert date to string (akshare returns datetime, CSV has strings)
            new_data["date"] = new_data["date"].astype(str).str[:10]

            # Append to existing file
            if os.path.exists(file):
                old = pd.read_csv(file, encoding="utf-8-sig", dtype={"date": str})
                # Deduplicate
                combined = pd.concat([old, new_data], ignore_index=True)
                combined = combined.drop_duplicates(subset=["date"], keep="last")
                combined = combined.sort_values("date").reset_index(drop=True)
            else:
                combined = new_data

            combined.to_csv(file, index=False, encoding="utf-8-sig")
            updated += 1

            if (i + 1) % 100 == 0:
                print(f"  [{i+1}/{len(stocks)}] {updated} updated...")

        except Exception as e:
            # Rate limiting / network errors
            if "暂未收录" in str(e) or "未上市" in str(e):
                continue
            continue

    print(f"  {updated}/{len(stocks)} stocks history synced")
    print("================")



if __name__=="__main__":

    update()